sudo: required

language: java

services:
  - docker

before_install:
  - docker build --build-arg LIBLOUIS_VERSION=liblouis_2_5_2 --build-arg BRAILLE_TABLES_VERSION=liblouis_2_5_2 -t sbsdev/dtbook2sbsform:legacy -f Dockerfile.test_with_utfx .

script:
  - docker run --rm --volume=$(pwd):/usr/src/dtbook2sbsform -t sbsdev/dtbook2sbsform:legacy
