# Create a Docker image in which we can still run the utfx tests.
# Those only run with an older version of Java

FROM debian/eol:jessie
RUN apt-get update && apt-get install -y \
    ant \
    autoconf \
    curl \
    libtool \
    make \
    pkg-config \
    texinfo

ARG LIBLOUIS_VERSION=master
ARG BRAILLE_TABLES_VERSION=master
WORKDIR /root/src/
RUN if [ "$LIBLOUIS_VERSION" = "master" ]; then curl -L https://github.com/liblouis/liblouis/archive/refs/heads/master.tar.gz | tar zx; else curl -L https://github.com/liblouis/liblouis/archive/refs/tags/v${LIBLOUIS_VERSION}.tar.gz | tar zx; fi

WORKDIR /root/src/liblouis-${LIBLOUIS_VERSION}/
RUN ./autogen.sh && \
    ./configure --enable-ucs4 && \
    make && \
    make install && \
    ldconfig

WORKDIR /root/src/
RUN if [ "$BRAILLE_TABLES_VERSION" = "master" ]; then curl -L https://github.com/sbsdev/sbs-braille-tables/archive/refs/heads/master.tar.gz | tar zx; else curl -L https://github.com/sbsdev/sbs-braille-tables/archive/v${BRAILLE_TABLES_VERSION}.tar.gz | tar zx; fi
WORKDIR /root/src/sbs-braille-tables-${BRAILLE_TABLES_VERSION}/
RUN ./autogen.sh && \
    ./configure && \
    make && \
    make install
RUN touch \
    /usr/local/share/liblouis/tables/sbs-de-g1-white.mod \
    /usr/local/share/liblouis/tables/sbs-de-g2-white.mod

WORKDIR /usr/src/dtbook2sbsform

ENTRYPOINT ["./utfx.sh"]
