#+TITLE: dtbook2sbsform

A command line tool to transform [[http://en.wikipedia.org/wiki/DTBook][dtbook xml source files]] into a
braille format proprietary to [[http://www.sbs.ch][Swiss Library for the Blind, Visually
Impaired and Print Disabled]] using [[http://saxon.sourceforge.net][Saxon]] with [[https://github.com/liblouis/liblouis-java][liblouis-java]] bindings
for translating text into braille using [[https://liblouis.io][liblouis]].

* Build

Requires Java 11+.

#+BEGIN_SRC shell
just deb
#+END_SRC

* Usage of command line tools

#+BEGIN_SRC shell
cd dtbook2sbsform
./dtbook2sbsform.sh dtbook.xml
#+END_SRC

calls =saxon.sh=, transforms =dtbook.xml= and performs line breaking
using =linebreak.sh= printing output onto stdout.

#+BEGIN_SRC shell
./saxon.sh
#+END_SRC

calls saxon, offering its rich command line interface, includes our
extension function (see =resources/xsl/dtbook2sbsform.xsl=).

#+BEGIN_SRC shell
./linebreak.sh
#+END_SRC

breaks lines according to sbs rules: only lines beginning with a blank
will be broken. Line width is 80 chars.

* Prerequisite installs
- [[http://java.sun.com][java]] 11+
- [[https://liblouis.io][liblouis]]
- =sbs-braille-tables= Debian package

* Testing

#+BEGIN_SRC shell
mvn test
#+END_SRC

To run a single XSpec file:

#+BEGIN_SRC shell
mvn test -Dtest="XSpecTest#run[src/test/xspec/FILENAME.xspec]"
#+END_SRC

All dependencies are on Maven Central — no local jar installs required.

* License

Copyright 2011-2026 Swiss Library for the Blind, Visually Impaired and Print Disabled.

Licensed under GNU Lesser General Public License as published by the
Free Software Foundation, either [[http://www.gnu.org/licenses/gpl-3.0.html][version 3]] of the License, or (at your
option) any later version.
